# Eureka server configuration
spring.application.name=EurekaServer

# Eureka dashboard and registry port
server.port=8761
# Eureka server should not register itself as a client
server.eureka.client.register-with-eureka=false
# Eureka server does not fetch registry entries from itself
server.eureka.client.fetch-registry=false
